version: 0.2

env:
  # variables:
  #   PACKAGE: "github.com/a-berahman/gitpipe"

  parameter-store:
    # store with: aws ssm put-parameter --name "<KEY>" --value "<VALUE>" --type String
    DOCKER_HUB_USERNAME: "docker_hub_username"
    DOCKER_HUB_PASSWORD: "docker_hub_password"
    IMAGE_REPO_NAME: "image_repo_name"
    IMAGE_TAG: "image_tag"

phases:

  install:
    commands:

  pre_build: 
    commands:
      - echo DOCKER_HUB_USERNAME ${DOCKER_HUB_USERNAME} Password ${DOCKER_HUB_PASSWORD} IMAGE_REPO_NAME ${IMAGE_REPO_NAME} IMAGE_TAG ${IMAGE_TAG}
      - echo Logging in to Docker Hub...
      - docker login -u ${DOCKER_HUB_USERNAME} -p ${DOCKER_HUB_PASSWORD}
      # - git clone https://github.com/a-berahman/gitpipe
      # - go get github.com/a-berahman/gitpipe


  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t ${IMAGE_REPO_NAME}:${IMAGE_TAG} .
      - docker tag ${IMAGE_REPO_NAME}:${IMAGE_TAG} ${IMAGE_REPO_NAME}:${IMAGE_TAG}
  
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push ${IMAGE_REPO_NAME}:${IMAGE_TAG}